### ISSUE TITLE
The plugin is using the Chinese replacements instead of the english one

### ISSUE THREAD

**Issue by mathisgauthey** [texousliu/open-gitmoji#17]
**Describe the bug**
Hey there. Thanks for the plugin, I'm having issues with the plugin that is using the CN version of the messages even though my IDE is configured in English.

**To Reproduce**
Start typing an emoji using `:` and type refactor.
Expect to get this :
![image](https://github.com/texousliu/open-gitmoji/assets/46576952/649968ed-51b7-472b-a7ff-87fd34f21d2e)
But get this :
![image](https://github.com/texousliu/open-gitmoji/assets/46576952/9e5b9c7f-cf69-4b96-9ed2-7cac83118b12)
And then this : 
![image](https://github.com/texousliu/open-gitmoji/assets/46576952/3ec64c36-9aea-4482-972e-f6bcfb51f96b)

**Environment:**
 - OS: Windows 11
 - Version 231.3.0.0
 - IDEA Version 2024.1.2

Thanks in advance !

**Comment by texousliu** [comment]
The default expression value is in Chinese. You can define the input content by customizing the expression on Prompt List.
![image](https://github.com/texousliu/open-gitmoji/assets/27934702/fd579238-e2c3-4150-aa27-a38358f5b16d)

**Comment by texousliu** [comment]
such as：
![image](https://github.com/texousliu/open-gitmoji/assets/27934702/80ebc206-db34-4fc4-9fed-a013b44325aa)

**Comment by mathisgauthey** [comment]
> The default expression value is in Chinese. You can define the input content by customizing the expression on Prompt List. ![image](https://private-user-images.githubusercontent.com/27934702/337656666-fd579238-e2c3-4150-aa27-a38358f5b16d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjU3ODQsIm5iZiI6MTcxNzc2NTQ4NCwicGF0aCI6Ii8yNzkzNDcwMi8zMzc2NTY2NjYtZmQ1NzkyMzgtZTJjMy00MTUwLWFhMjctYTM4MzU4ZjViMTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEzMDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZDQxZjJlYzRjODk0NGZkMzg1YzBmMmE5YjVjZGFlNWNjZGM2N2MwNDE4MTNjNTNhNzdlMDE1MzdhNTBkMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ARxKOa3iSBOhRsQ_g6--65zXAakdV8c3MHHRWpnsWYA)

Hey there ! Thanks you for the help, it works as intended now ! Have a great day o/
